branch-defaults:
  develop:
    environment: oishikatta-dev
global:
  application_name: oishikatta
  branch: null
  default_ec2_keyname: oishikatta-eb
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
