<?php

namespace AppBundle\Repository;
use \Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
    public function getParentIngredients()
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.parent = 0')
            ->select('i.id, i.name');

        $results = $query->getQuery()->getResult();
//
        $arrayParent = array();

        foreach ($results as $r) {
            $arrayParent[$r['name']] = $r['id'];
        }

        return $arrayParent;
    }

    public function findOrderedIngredients($parentId)
    {
        return $this->createQueryBuilder('i')
            ->where('i.parent = ' . $parentId)
            ->orderBy('i.name', 'ASC')
            ->getQuery()->getResult();
    }

}