<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLatestRecipes(){
        return $this->createQueryBuilder('r')
            ->select('r, c')
            ->leftJoin('r.country', 'c')
            ->orderBy('r.updatedAt', 'DESC')
            ->getQuery()->getArrayResult();
    }

    public function searchRecipe($searchText){
        $query = $this->createQueryBuilder('r')
            ->select('r, c')
            ->leftJoin('r.country', 'c')
            ->where("r.name LIKE '%".$searchText."%'")
            ->orderBy('r.updatedAt', 'DESC')
            ->getQuery();

        return $query->getArrayResult();
    }
}
