<?php

namespace AppBundle\Repository;

/**
 * RecipeStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeStepRepository extends \Doctrine\ORM\EntityRepository
{
}
