<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLatestRecipes(){
        return $this->createQueryBuilder('r')
            ->select('r, c')
            ->leftJoin('r.country', 'c')
            ->orderBy('r.createdAt', 'DESC')
            ->getQuery()->getArrayResult();
    }
}
